// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUw8v2RaQLcskQZjP3eS-PZicMHX_F6B4',
    appId: '1:550005067823:web:a315a12790d79f4d7776da',
    messagingSenderId: '550005067823',
    projectId: 'sparkhub-fd482',
    authDomain: 'sparkhub-fd482.firebaseapp.com',
    storageBucket: 'sparkhub-fd482.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwiV_4GR_k-AWipTeOZaMjAszrTdasdnM',
    appId: '1:550005067823:android:50e0454f40d3530b7776da',
    messagingSenderId: '550005067823',
    projectId: 'sparkhub-fd482',
    storageBucket: 'sparkhub-fd482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHRh85AtU5MEETp4NCUQyGH7dM369ZLw',
    appId: '1:550005067823:ios:0abd39d425a6ea767776da',
    messagingSenderId: '550005067823',
    projectId: 'sparkhub-fd482',
    storageBucket: 'sparkhub-fd482.firebasestorage.app',
    iosBundleId: 'com.example.sparkhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVHRh85AtU5MEETp4NCUQyGH7dM369ZLw',
    appId: '1:550005067823:ios:0abd39d425a6ea767776da',
    messagingSenderId: '550005067823',
    projectId: 'sparkhub-fd482',
    storageBucket: 'sparkhub-fd482.firebasestorage.app',
    iosBundleId: 'com.example.sparkhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUw8v2RaQLcskQZjP3eS-PZicMHX_F6B4',
    appId: '1:550005067823:web:5792e8ec04fcb3af7776da',
    messagingSenderId: '550005067823',
    projectId: 'sparkhub-fd482',
    authDomain: 'sparkhub-fd482.firebaseapp.com',
    storageBucket: 'sparkhub-fd482.firebasestorage.app',
  );
}
